version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      # Install required dependencies for building Python with SQLite support
      - sudo yum install -y \
            gcc make bzip2 bzip2-devel zlib-devel xz-devel \
            libffi-devel readline-devel sqlite-devel \
            tk-devel wget curl llvm \
            openssl-devel
      # Rebuild Python 3.13.7 with SQLite support
      - pyenv uninstall -f 3.13.7
      - pyenv install 3.13.7
      - pyenv global 3.13.7
      - pip install -r requirements.txt
      - pip install flake8 pytest coverage
      - echo "Installing Trivy..."
      - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
  build:
    commands:
      - echo "Running lint checks..."
      - flake8 app tests --max-line-length=100
      - echo "Running tests..."
      - coverage run -m pytest
      - coverage report
      - echo "Running Trivy scan..."
      - trivy fs . --exit-code 0 --severity HIGH,CRITICAL --ignore-unfixed --no-progress
reports:
  coverage-report:
    files:
      - coverage.xml
    file-format: JACOCOXML
artifacts:
  files:
    - coverage.xml
